title: Tokyo Developers!
email: your-email@example.com
description: >
  Meetup for developers in Tokyo from all walks of life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "tokyodevelopers.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed